### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by joopvdl** [freddyz/computerscare-vcv-modules#1]
A reset button and trig input would be very useful, one that resets the module to step 1. Could of course also be called a step one button/trig :)

**Comment by freddyz** [comment]
I think that is a good idea - I will include it in the next release.  Thanks for the suggestion!

**Comment by joopvdl** [comment]
Yes!

**Comment by freddyz** [comment]
Alright the latest version now has a reset button and input jack.  I've put in a request to have the version in plugin manager updated, but until then you can build yourself!  Thanks again for the suggestion!
