### ISSUE TITLE
Porting to v1?

### ISSUE THREAD

**Issue by espenstoro** [freddyz/computerscare-vcv-modules#13]
Hi. Just wanted to say that your modules are missed, wondering if you're about to join the v1 party? :)
I feel helpless without Laundry soup. ;)

Cheers,
ES

**Comment by freddyz** [comment]
Hi!  I've successfully ported 3 of 5 of the modules.  Currently working on Laundry Soup.  It's awesome to hear that you enjoy the modules - I hope to have them finished and available in the plugin manager soon!

**Comment by freddyz** [comment]
<img width="858" alt="Screen Shot 2019-07-03 at 8 47 51 PM" src="https://user-images.githubusercontent.com/1319733/60634249-eb215000-9dd3-11e9-824c-5b7e50c384b0.png">
Finally generating a sequence without crashing!  I'm a total C++ novice so this has been a bit of a struggle...

**Comment by espenstoro** [comment]
Very nice. I know nothing about programming, but I know that it's by far the best clock divider/trigger sequencer ever made in Rack. Nothing else lets me paste hundreds of digits of pi. ;)

**Comment by FMTolstoevsky** [comment]
Nice to see you at work, freddyz! My biggest fav which I used very often in 0.62 patches is Cookies :) Really great and very under-rated module, BTW!

**Comment by freddyz** [comment]
v1.0.0 is now in the plugin manager: https://vcvrack.com/plugins.html#computerscare
