### ISSUE TITLE
v1 compile error [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [freddyz/computerscare-vcv-modules#14]
`g++  -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ComputerscareLaundrySoup.cpp.o src/ComputerscareLaundrySoup.cpp
src/ComputerscareLaundrySoup.cpp: In member function 'virtual void LaundryTF2::draw(const rack::widget::Widget::DrawArgs&)':
src/ComputerscareLaundrySoup.cpp:313:35: error: 'index' was not declared in this scope
  313 |           printf("in error %i\n", index);`

Shouldn't index be rowIndex?

I changed this and build was successful.

**Comment by davephillips** [comment]
Same error on Fedora 23 Linux. Same fix worked here too. Thanks @SteveRussell33 ! :)

**Comment by freddyz** [comment]
Yes indeed.  I'll make a new commit soon.  Thank you for the report!

**Comment by SteveRussell33** [comment]
You're welcome!
