### ISSUE TITLE
LaundrySoup 1.2.0 does NOT recall old patches

### ISSUE THREAD

**Issue by Petervos2018** [freddyz/computerscare-vcv-modules#33]
This is the original patch : 
![ScareOld](https://user-images.githubusercontent.com/46076474/71027474-a2541e00-210b-11ea-91bb-878475016231.png)

And after updating to 1.2.0 it looks (and sounds) like this : 

![ScareNew](https://user-images.githubusercontent.com/46076474/71027525-b9930b80-210b-11ea-93b2-3d24dee5fad8.png)

And the sixth row is always different with every new LaundrySoup, maybe intentional as a nice random setting?

Greetings Peter.

**Comment by freddyz** [comment]
Dang I thought I fixed that.  Could you upload the .vcv file?

**Comment by Petervos2018** [comment]
Sure it a big patch but maybe it's useful to you 

[Lulu rouge 64-4 rithm - 13092019-3Automation3 TEMP2.zip](https://github.com/freddyz/computerscare-vcv-modules/files/3975120/Lulu.rouge.64-4.rithm.-.13092019-3Automation3.TEMP2.zip)

Greetings Peter.

**Comment by freddyz** [comment]
Thanks.  Also, which platform are you running Rack on?  

The 6th row random initial formula is intentional, but obviously overwriting your previous values is not!

**Comment by Petervos2018** [comment]
Windows 7 
And I guessed the random row was a nice touch :+1:

**Comment by Petervos2018** [comment]
I'm on Win 10 now and I still have this issue.

**Comment by freddyz** [comment]
Thanks for the update.  Is this the case for any patch with Laundry Soup, or just the patch you uploaded above?

**Comment by Petervos2018** [comment]
To be honest I "THINK" it goes wrong with all the Laundry soups prior to 1.2.0. , but I have not tried this, furthermore I "THINK" that when I save a patch with 1.2.0 and recall it it will probably be OK. But it's a lot of work deleting the folder swapping them out etc....

Greetings Peter (maybe I'll try it later)

**Comment by Petervos2018** [comment]
Yep just tested it's EXACTLY like I wrote above and here are 2 simple patches one made with 111 the other with 120 they both should go from 10 (top) to 5 (bottom) and depending on what version you have installed the 111 reads them both the right way, 120 Fux the 111 up and loads the 120 OK.

Greetings Peter.

[patches-v1.zip](https://github.com/freddyz/computerscare-vcv-modules/files/4124105/patches-v1.zip)

**Comment by freddyz** [comment]
Do I have this correct?

| Laundry Soup Patch Version        | Running Computerscare Modules 1.1.1      | Running Computersare modules 1.2.0  |
| ------------- |:-------------:| -----:|
| 1.1.1      | Loads properly | Does not load properly|
| 1.2.0     | Loads properly      |   Loads properly |

Thanks a lot for testing this!

**Comment by Petervos2018** [comment]
Yes that is a very nice representation of the nonsense I wrote above. 👍

**Comment by freddyz** [comment]
Thanks for sending those patch files - now I can reproduce the problem and I see that it affects some other parts of Laundry soup as well.

**Comment by Petervos2018** [comment]
Thank you for investigating 👍

**Comment by freddyz** [comment]
Alright I think I've fixed the problem.  You can test it out with a build of 1.3.0 here: https://github.com/freddyz/computerscare-vcv-modules/releases/tag/v1.3.0

**Comment by Petervos2018** [comment]
Yes that did it, 
well done Adam/freddyz thank you for sorting this out (for me).
I'm gonna close this one NOW.
Greetings Peter.
