### ISSUE TITLE
Can we have different scales for knob values in 'I love cookies'?

### ISSUE THREAD

**Issue by 77377** [freddyz/computerscare-vcv-modules#35]
Hi, l love this sequencer a lot, thank you for making and maintaining it!

Would you be so kind as to add an option for the knob ranges? I can live with 0v-10v but for some purposes -5v-5v or -1v-1v would be more practical. Cheers!

**Comment by freddyz** [comment]
I like it.  In the next release I will include a right-click option to select various knob ranges.

Thanks for the kind words, I'm glad you enjoy the module!

**Comment by freddyz** [comment]
How does this look for knob ranges selectable via right click:
<img width="420" alt="Screen Shot 2020-03-26 at 8 24 00 PM" src="https://user-images.githubusercontent.com/1319733/77711775-e2932a00-6f9f-11ea-8c6b-1f85243c67f3.png">

**Comment by sami-befree** [comment]
Awesome !
It’s so frustrating when the range you need is missing ;0)
Knob range is a killer idea!
