### ISSUE TITLE
Custom blank animated gif request

### ISSUE THREAD

**Issue by vcvrackideas** [freddyz/computerscare-vcv-modules#49]
Hi and thanks for this awesome module! I'd really like to look at animated gifs while patching however) is that possible? Loading gif is totally ok but they are stuck just in one frame. I mean movement of things pretty inspires me for some musical ideas sometimes. Thanks again! I'm on windows btw if that makes sense

**Comment by freddyz** [comment]
That would be cool, I will look into it for the next Computerscare Modules version (1.4.0).  By the way is this Artem?  If so I enjoy your music and your video tutorials!

**Comment by vcvrackideas** [comment]
> That would be cool, I will look into it for the next Computerscare Modules version (1.4.0). By the way is this Artem? If so I enjoy your music and your video tutorials!

Yeah, here I am) thanks for very kind words! and very looking forward to it, that would be very fun. I think we can even use some video to gif converters if this will work, huge addition for audiovisuals people. Just let me know if you need some kind of testing, I can easily build it on windows from a source

**Comment by freddyz** [comment]
Research notes:
https://github.com/memononen/nanovg/blob/master/src/nanovg.c
int nvgCreateImage uses stbi_load

https://github.com/nothings/stb/blob/master/stb_image.h claims there is a "way to do" animated gif per: https://gist.github.com/urraka/685d9a6340b26b830d49

**Comment by nnbveh** [comment]
Hi. Use the custom blank today being sure that the gif will animate, unfortunately not the case...i really hope you can implement it, and while you're at it, how about cv inputs for playback control? Maybe one would be enough actually, just a trigger/gate, every time trigger received  - advances one frame, gate/stable voltage in - plays with the normal speed?

Thanks!

**Comment by freddyz** [comment]
Greetings!  I'm looking into it.  Once I determine how much work it would be / if it's possible I'll post an update here.

**Comment by freddyz** [comment]
@vcvrackideas @nnbveh looks possible!  Still pretty buggy but I'm pretty confident I'll have some sort of animated gif support in the next computerscare modules release
![blank-animated-gif-demo-short](https://user-images.githubusercontent.com/1319733/89647042-7f38d300-d882-11ea-8248-a34aca1e7213.gif)

**Comment by nnbveh** [comment]
Hi there! Any progress on this? Would be really cool to have animated
blanks in VCV!

**Comment by freddyz** [comment]
Yeah I'm pretty sure I'll have it for the next release but there's some major bugs that I'm having trouble resolving.  Shooting to have it finished and released in 2020 still.

**Comment by freddyz** [comment]
I've got a beta build of the new plugin available here: https://github.com/freddyz/computerscare-vcv-modules/releases/tag/v1.4a

If either of y'all @nnbveh @vcvrackideas would be interested in taking a look at the new module.  I kept adding more and more features, and eventually an expander module (Custom Blank Expander) for CV control of the GIF animation,

**Comment by vcvrackideas** [comment]
Hi! Thanks for that. Unfortunately I can't upload any gif into that, it shows me "broken file" messages. Tested 3 random gifs from internet

**Comment by freddyz** [comment]
Could you upload these problem gifs here?  I collected a bunch of random internet gifs as well to develop this, and there were a few that are not loadable by the image loading library that is included in Rack.

**Comment by vcvrackideas** [comment]
Yes, you're right. Only one gif from google's search is a problem - https://commons.wikimedia.org/wiki/File:FullColour.gif
Just curious why is that. Thanks, some others seems work nice! And yeah the last one works but with glitching artifacts, no like in browser - https://en.wikipedia.org/wiki/File:Animated_Wallpaper_Windows_10_-_Wallpaper_Engine.gif

**Comment by freddyz** [comment]
Thank you for the examples.  I can witness the problem in each of these gifs, and indeed I've seen both of these issues in my prior testing using different gifs.  I didn't create the part of the code that actually loads and displays the individual GIF frames, I am merely using it so I don't have any insight into what the problem with these files is other than an error message in one case, and this weird glitchy behavior in the other.  I'm not going to delay the release, so I think we'll have to deal with some GIFs not working right for now.  But, thank you again for providing these samples and for the initial feature request.  I've learned a lot about both animated GIFs, and more about developing for Rack!

**Comment by freddyz** [comment]
v1.4 is released to the Library with animated GIF support.  It's not perfect, some GIFs don't load for unknown reasons but I will deal with that in separate issues as it comes up:
https://github.com/freddyz/computerscare-vcv-modules/issues/61
https://github.com/freddyz/computerscare-vcv-modules/issues/60

Thanks again for the request.  This took me quite a while but it was pretty fun to develop this feature.

**Comment by nnbveh** [comment]
Cool, uploading a video already using it))

How about making the width resizeable? I know there's at least one
oscilloscope which can do that.

**Comment by freddyz** [comment]
> How about making the width resizeable?
Custom Blank has been resizable since its initial release.  click and drag on either the far left or far right side of the module.  Also check the right click menu for the keyboard controls to move the image around and zoom in/out.

**Comment by nnbveh** [comment]
Yes, I thought it was, but then I've tried and couldn't resize it so I
thought I remembered wrong! Will try again. Thanks!
