### ISSUE TITLE
Optionally allow CustomBlank image to display at full opacity when used with ModularFungi Lights Off

### ISSUE THREAD

**Issue by Jorgill** [freddyz/computerscare-vcv-modules#59]
On the Computerscare Blank module would it be possible to have an option to protect it from "dimming" by the Modular Fungi Lights Off module? I use the Computerscare Blank module so I can include a JPG in my patch for inspiration, and it works great for that, It'd be super cool to be able to lights off the whole patch, but keep the Computerscare blank protected so it remains at normal brightness.

**Comment by freddyz** [comment]
Greetings Jorgill, thank you for the suggestion I will look into it and if it's do-able I'll plan on including this feature in the upcoming release.  I don't use Lights Off myself, but I am aware that some modules work well with it and others do not.  Do you know of any modules that have an "on/off" setting like what you're suggesting?  I'd imagine that some users might want it to remain bright, while others might want it to go dim so ideally I'd provide the option.

**Comment by Jorgill** [comment]
Hi and thanks for getting back to me!
I don’t know of any other modules that have a lights off “immunity” switch, but that’s a great idea. I’ll see if I can find one and let you know if I do. 

I can see some really beautiful VCV layouts using a combo of lights out and computerscare photo panels-they definitely add a great visual!

- Jeff

**Comment by freddyz** [comment]
I actually figured it out!  It will be in the next release, which will be "soon", but I have one major bug to fix before submitting to the library

**Comment by freddyz** [comment]
v1.4 is out in the Library, check the right click menu of Custom Blank for your feature!  Thanks again for the request, glad you enjoy the module.

**Comment by Jorgill** [comment]
It’s a glowing achievement!

Muchas gracias!!!

- Jeff
