### ISSUE TITLE
Oh peas! does not recall settings correctly after reloading project 

### ISSUE THREAD

**Issue by Petervos2018** [freddyz/computerscare-vcv-modules#6]
title says it all , when I reload a project I have to twiddle the divisions knob (maybe other knobs also work, didn't test, just tested other knobs also work) to get it going.
Even tough I have a C minor scale selected it plays an E and a B after wiggling the knob it jumps to D# and A# which is  correct.
I guess it recalls the default major scale ?
Windows 7 

Greetings Peter

**Comment by freddyz** [comment]
Thanks - I was able to reproduce the problem and will release a fix shortly.

**Comment by freddyz** [comment]
I've made a fix and the new version (0.6.6) is available via the plugin manager.  @Petervos2018 could you confirm that the Oh Peas! scale is behaving as you expect after saving and re-loading a patch.  Thanks again for the bug report!

**Comment by Petervos2018** [comment]
Hi Adam,
As far as I can tell it's reloading a patch as it should, so bug squashed !

Thanks for the fix and all your modules, they are weird but very useful.
