### ISSUE TITLE
toly pools feature request

### ISSUE THREAD

**Issue by glocke01** [freddyz/computerscare-vcv-modules#66]
I want to be able to rotate N input channels across N output channels while ignoring the empty inputs.

Possible implementations: 
suggestion A: special behavior when input and output channels are the same. given input at channel **i** with rotate set to **j** goes to output channel **(i+j)%N** 
suggestion B: rotate ignores empty channels. If output channels > input channels, then duplicate input channels

Request: Rotate should ignore empty channels. Given **N** channels at input, rotate **j** should behave the same as rotate **j+N**. If there are three poly channels bearing signals A, B, C, rotate should 

rotate=0: A, B, C, (A, B, C, A, B, C, A, B, C, A)
rotate=1: B, C, A, (B, C, A, B, C, A, B, C, A, B)
rotate=2: rotate=0: C, A, B, C, (A, B, C, A, B, C, A, B, C)
rotate=3=0: A, B, C, (A, B, C, A, B, C, A, B, C, A)

Given inputs A, B, C, D, 
rotate=0: A, B, C, D, (A, B, C, D, A, B, C, D, A, B, C, D)
rotate=1: B, C, D, A, (B, C, D, A, B, C, D, A, B, C, D, A)

and so on.

**Comment by glocke01** [comment]
I see that soly pequencer can already do this. Maybe I'll just use that - maybe instead can you add a manual button (clock advance) to soly pequencer?

**Comment by freddyz** [comment]
Soly Pequencer does have a manual clock advance button, click the "clk" text that doesn't look like a button :)

Your rotation suggestion for Toly Pools seems useful though, I'll plan on adding it as an optional mode so as not to break any existing patches

**Comment by glocke01** [comment]
Thanks for the quick response. I just noticed the button, so my needs are basically met for the meantime.

Awesome collection! I've been using VCV for a long time but I'm finally just beginning to explore mour yodules. Stool cuff.

**Comment by freddyz** [comment]
Glad to hear it!  Thanks for the suggestion.  Also check out Roly Pouter, which can arbitrarily re-route a poly signal.  The latest release includes CV control so you should also be able to accomplish it using that module, perhaps easier.

**Comment by freddyz** [comment]
This has been implemented in v2.1.11
