### ISSUE TITLE
Can you fail quietly when an image for the custom blank doesn't exist on another persons machine?

### ISSUE THREAD

**Issue by jeremywen** [freddyz/computerscare-vcv-modules#67]
it hard crashed his rack when i sent him a patch with an image i had

**Comment by freddyz** [comment]
Shoot, yeah I thought I was handling that gracefully with a "missing image" display but I must have missed something.  Thanks for the report

**Comment by freddyz** [comment]
Should be fixed in new library version, 1.42.  Thanks again!
