### ISSUE TITLE
Custom Blank animation frame length 

### ISSUE THREAD

**Issue by jaynothin** [freddyz/computerscare-vcv-modules#69]
I just discovered you added the animation in Custom Blank module, and decide to give it a try :)
The animations I tried were 2 stickman animated gif
I came to the conclusion that you have only allowed 128 frames if I'm correct??

So, this is more of a request than a bug issue 😄 

Would it be possible in a future upgrade to increase the length ??
I don't know how much, but I'm posting a gif so you understand how much of an increase it could be.

![Stickman Course](https://user-images.githubusercontent.com/74117050/132598907-b948a04b-552c-4eb6-a261-03fc70b5fe57.gif)

In VCV, you can see that the stickman doesn't even make it to the floor below the top one and even thought most gif are pretty small, it would be very nice to play longer ones in VCV 😉 

In the meantime, I'll try to find smaller gifs 🤣

**Comment by freddyz** [comment]
You are correct, for some reason I have limited the GIF frames to 128 for a totally unknown reason.  Might have been a good reason, may have been a bad or arbitrary reason?  I'll take a look at this and plan on removing the frame limit in the next release.

Awesome GIF by the way!

**Comment by freddyz** [comment]
Version v1.4.3 of computerscare Modules is now available in the VCV Library, this problem is now fixed.  Thanks for the report!
