### ISSUE TITLE
Draw on the lights layer

### ISSUE THREAD

**Issue by jpnielsen** [freddyz/computerscare-vcv-modules#76]
I have a request.

Can you make an option to have `Custom Blank` draw on the "lights" layer in Rack 2 ?

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/27916597/145717802-6222b8bd-9ce9-43bb-bdf0-f90e1c408bc8.png">

My nixies dim when i lower the Room Brightness.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/27916597/145717831-7c9827d5-bff2-497c-9ff6-2d022684e0ab.png">

Best regards,
Jens Peter Nielsen

**Comment by freddyz** [comment]
This feature is already available via the Custom Blank right click menu: "keep image fully opaque when dimming room lights"

<img width="503" alt="Screen Shot 2021-12-12 at 9 51 33 AM" src="https://user-images.githubusercontent.com/1319733/145719350-595c4914-592e-46ce-acd5-7147a96eeb59.png">
"
