### ISSUE TITLE
v1 crashing Rack

### ISSUE THREAD

**Issue by davephillips** [freddyz/computerscare-vcv-modules#8]
Fedora 23 Linux
GCC 5.3.1
Rack v1.dev.7b0c04a 

Alas, your plugin still crashes Rack from the browser. See the full debug report at  https://pastebin.com/z1UyFuE1

Best regards,

Dave Phillips

**Comment by freddyz** [comment]
I just committed a fix for this to the v1 branch - could you confirm that the plugin no longer crashes the module browser?

**Comment by davephillips** [comment]
@freddyz That did the trick, thank you ! :)
