### ISSUE TITLE
Compilation failed : app.hpp not found

### ISSUE THREAD

**Issue by zebulon-1st** [freddyz/computerscare-vcv-modules#81]
System : Debian GNU/Linux 11 (bullseye)
$ uname -a : Linux debian-1 5.10.0-14-amd64 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

I put here only the first error of this type. There are many (counted 8).
```
In file included from src/ComputerscareFolyPace.cpp:3:
src/Computerscare.hpp:11:10: fatal error: app.hpp: Aucun fichier ou dossier de ce type
   11 | #include "app.hpp"
      |          ^~~~~~~~~
```

I searched for it in the all Rack sources directory : nothing
with apt-file search : nothing

Where is this file from ?

Best regards.

**Comment by freddyz** [comment]
Hi!  It looks like I used a separate branch to update computerscare modules to v2.  Try checking out and building the [v2.0.2 branch](https://github.com/freddyz/computerscare-vcv-modules/tree/v2.0.2) if you're looking to build yourself.  Master hasn't been updated.
