### ISSUE TITLE
Laudry Soup "offset" command issue

### ISSUE THREAD

**Issue by mizi0** [freddyz/computerscare-vcv-modules#9]
Lately, after updating to 0.6.6, i noticed the offset command (-) is no longer recognized by the plugin; if i enter 8-4 the display goes red (error?).
Am i the only one? 

(win7 ultimate x64, i5-3750, 16gb ram, gtx 970 4gb)

**Comment by freddyz** [comment]
Yes you're right about that - I haven't updated the documentation or screenshots.
The way to do an offset now is to use a "0" which is interpreted as a 1-step "rest".

So, the old input:"8-4" (8 offset by 4) rhythm should now be programmed as "00004" or equivalently "0@4, 4".

Thanks for the report - sorry about the undocumented change.  I am planning on handling the "-" offset syntax again in the v1 release of the module.

**Comment by freddyz** [comment]
Update: I'm afraid I decided not to implement the "-" offset syntax for the v1 release.  As I mentioned above, using "0" as a blank step along with the "@" symbol lets you accomplish the same thing.
